### ISSUE TITLE
remove extra bottom margin in Pds::Banner

### ISSUE THREAD

**Issue by noelledaley** [hashicorp/structure#67] opened 2021-03-22 19:20 UTC
As pointed out by @joshuaogle, the `pds::banner` has slightly too much bottom margin when no banner footer is included.

A potential solution is:
```
.pds-banner__body > *:last-child {
    margin-bottom: 0;
}
```
https://github.com/hashicorp/cloud-ui/pull/762/#issuecomment-803055973

**Comment by MooCohen** [comment] 2021-04-20 22:56
Closing this because the issue is with `cloud-ui` and the `AlertBanner` content, this component has consistent padding.
<img width="638" alt="Screen Shot 2021-04-20 at 3 47 33 PM" src="https://user-images.githubusercontent.com/4605060/115473676-00f24600-a1f1-11eb-9548-9d10c0512790.png">

**Closed by MooCohen** 2021-04-20 22:56 UTC
